var owin = 
    "<div id=\"oc_mWindow\" style=\"LEFT: expression(document.body.clientWidth/2-this.offsetWidth/2);TOP: expression(document.body.clientHeight/2-this.offsetHeight/2+15); BORDER-COLLAPSE: collapse\">"
    +"<div id=\"oc_mWindow_head_left\"><img src=\"1_1.gif\" border=\"0\" /></div><div id=\"oc_mWindow_head\"><img src=\"1_1.gif\" border=\"0\" /></div>"
    +"<div id=\"oc_mWindow_head_right\"><img src=\"1_1.gif\" border=\"0\" /></div><div id=\"oc_mWindow_title_left\"><img src=\"1_1.gif\" border=\"0\" /></div>"
    +"<div id=\"oc_mWindow_title\"><div id=\"oc_mWindow_title_text\">详细资料</div><div id=\"oc_mWindow_title_close\"><img src=\"images/gif/关闭按钮.gif\" border=\"0\" onclick=\"closeOcWin()\" /></div></div>"
    +"<div id=\"oc_mWindow_title_right\"><img src=\"1_1.gif\" border=\"0\" /></div><div id=\"oc_mWindow_body_left\"><img src=\"1_1.gif\" border=\"0\" /></div>"
    +"<div id=\"oc_mWindow_body\"><div id=\"oc_mWindow_alert\"></div>"
    +"</div><div id=\"oc_mWindow_body_right\"><img src=\"1_1.gif\" border=\"0\" /></div><div id=\"oc_mWindow_confirm_left\"><img src=\"1_1.gif\" border=\"0\" /></div><div id=\"oc_mWindow_confirm\">"
    +"          <a href=\"#\" class=\"linkbtn_0\" onclick=\"_btnok()\">【确定】</a><a href=\"#\" class=\"linkbtn_0\" onclick=\"closeOcWin()\">【返回】</a>"
    +"</div><div id=\"oc_mWindow_confirm_right\"><img src=\"1_1.gif\" border=\"0\" /></div><div id=\"oc_mWindow_foot_left\"><img src=\"1_1.gif\" border=\"0\" /></div>"
    +"<div id=\"oc_mWindow_foot\"><img src=\"1_1.gif\" border=\"0\" /></div><div id=\"oc_mWindow_foot_right\"><img src=\"1_1.gif\" border=\"0\" /></div>"
    +"<iframe id=\"iframebg\" src=\"javascript:false\" style=\"position:absolute; visibility:inherit; top:0px; left:0px; width:100%; height:100%; z-index:-1; filter='progid:DXImageTransform.Microsoft.Alpha(style=0,opacity=0)';\"></iframe></div>";

var tablemake ="<table border=\"1\" cellspacing=\"0\" width=\"100%\" bordercolorlight=\"#333333\" bordercolordark=\"#efefef\" bgcolor=\"#D4D0C8\">"
+"  <tbody>"
+"    <tr>"
+"      <td width=\"46%\" colspan=\"3\" align=\"center\" height=25>用户信息　<a href=\"#\" class=\"linkbtn_0\" onclick=\"dlgwinpre(1,'grid')\">【查阅】</a></td>"
+"      <td width=\"54%\" colspan=\"4\" align=\"center\">卡片信息</td>"
+"    </tr>"
+"    <tr>"
+"      <td width=\"10%\" align=\"right\">姓　名：</td>"
+"      <td width=\"15%\">"
+"        <INPUT datasrc=\"#MasterTab\" datafld=\"name\" isnull=true class=\"xlandinput\" style=\"width:98%;\" type=\"text\" size=\"11\" name='姓名' />"
+"      </td>"
+"      <td width=\"20%\" align=\"center\" rowspan=\"7\">"
+"        <IMG src=\"Floppy.gif\" id=\"字典信息:pic\" class=\"xlandImg\" onload=\"javascript:if(this.width>160){this.resized=true;this.style.width=160;}\"  alt=\"个人照片\" />"
+"      </td>"
+"      <td width=\"11%\" align=\"right\">卡序列号：</td>"
+"      <td width=\"18%\">"
+"        <INPUT id=\"cardid\" class=\"xlandinput\" isnull=true name='卡序号' style=\"width:98%;\" type=\"text\"  size=\"11\" />"
+"      </td>"
+"      <td width=\"9%\" align=\"right\">个人密码：</td>"
+"      <td width=\"14%\">"
+"        <INPUT datasrc=\"#MasterTab\" datafld=\"cardkey\" class=\"xlandinput\" style=\"width:98%;\" type=\"text\" size=\"11\" name=\"姓名36\" /></td>"
+"    </tr>"
+"    <tr>"
+"      <td width=\"10%\" align=\"right\">编　号：</td>"
+"      <td width=\"15%\">"
+"        <INPUT datasrc=\"#MasterTab\" datafld=\"EMPCODE\" isnull=true name='工号' class=\"xlandinput\"　id=\"EMPCODE\" style=\"width:98%\" type=\"text\" size=\"11\"  />"
+"      </td>"
+"      <td width=\"11%\" align=\"right\">押金金额：</td>"
+"      <td width=\"18%\">"
+"        <INPUT datasrc=\"#MasterTab\" datafld=\"foregift\" class=\"xlandinput\" style=\"width:98%;\" type=\"text\" size=\"11\" name=\"姓名33\" /></td>"
+"      <td width=\"9%\" align=\"right\">付款金额：</td>"
+"      <td width=\"14%\">"
+"        <INPUT datasrc=\"#MasterTab\" datafld=\"balance\" class=\"xlandinput\" style=\"width:98%;\" type=\"text\" size=\"11\" name=\"姓名35\" /></td>"
+"    </tr>"
+"    <tr>"
+"      <td width=\"10%\" align=\"right\">卡　号：</td>"
+"      <td width=\"15%\">"
+"        <INPUT datasrc=\"#MasterTab\" datafld=\"card_no\" isnull=true name='卡号' class=\"xlandinput\" style=\"width:98%\" type=\"text\" size=\"11\"  />"
+"      </td>"
+"      <td width=\"52%\" align=\"right\" colspan=\"4\" rowspan=\"13\">"
+"        <TABLE align=\"center\" id=\"secTable\" cellSpacing=\"0\" cellPadding=\"0\" width=\"99%\" border=\"0\"  style=\"border-bottom-width: 0px;font-size:10pt\">"
+"          <TBODY>"
+"            <TR align=\"middle\" height=\"20px\">"
+"              <TD id='消费系统'  class=\"sec2\" onclick=\"secBoard(0);createdata(0);\" width=\"18%\" style=\"display:none;border-bottom-style: none; border-bottom-width: medium;height:16px\">消费"
+"<input id=\"消费\" type=\"checkbox\" name=\"syschk\" value=\"2\" onclick=chkitem(0);></td>"
+"              <TD id='门禁系统' style=\"display:none;\" class=\"sec1\" onclick=\"secBoard(1);createdata(1);\" width=\"18%\">门禁"
+"<input id=\"门禁\" type=\"checkbox\" name=\"syschk\" value=\"1\"  ></td>"
+"              <TD id='考勤管理' style=\"display:none;\" class=\"sec1\" onclick=\"secBoard(2);createdata(2);\" width=\"18%\">考勤"
+"<input id=\"考勤\" type=\"checkbox\" name=\"syschk\" value=\"3\" ></td>"
+"              <TD id='停车场' style=\"display:none;\" class=\"sec1\" onclick=\"secBoard(3);createdata(3);\" width=\"18%\">停车场"
+"<input id=\"停车场\" type=\"checkbox\" name=\"syschk\" value=\"0\" ></td>"
//+"              <TD id='巡更管理' style=\"display:none;\" class=\"sec1\" onclick=\"secBoard(4)\" width=\"18%\">巡更"
//+"<input id=\"巡更\" type=\"checkbox\" name=\"syschk\" value=\"ON\"></td>"
//+"              <TD id=\"tdfix\" class=\"secx\"  width=\"10%\" style=\"background-color: #D4D0C8\"></td>"
+"            </tr>"
+"          </tbody>"
+"        </table>"
+"        <TABLE align=\"center\" class=\"main_tab\" id=\"mainTable\" cellSpacing=\"0\" cellPadding=\"0\" width=\"99%\" border=\"0\" style=\"border-top-width: 0px\" height=\"310px\">"
+"          <!--菜单一内容-->"
+"          <TBODY style=\"DISPLAY: none\">"
+"            <TR>"
+"              <TD align=\"center\" height=\"2\" width=\"99%\" colspan=\"4\" >　</td>"
+"            </tr>"
+"            <TR>"
+"              <TD align=\"center\" height=\"25\" width=\"24%\" >卡类型：</td>"
+"              <TD height=\"25\" width=\"24%\" >"
+"                <SELECT datasrc=\"#eatery\" datafld=\"cardtype\" isnull=true class=\"xlandselect\" size=\"1\" style=\"WIDTH: 98%;\" name=\"消费卡类型\">"
+"                  <option value=\"\"></option><option value=\"1\">管理员</option><option value=\"2\">操作员</option>"
+"                  <option value=\"3\">员工卡</option><option value=\"4\">就餐卡</option><option value=\"5\">临时卡</option>"
+"                  <option value=\"6\">免费卡</option><option value=\"7\">临免卡</option><option value=\"8\">贵宾卡</option></SELECT></td>"
+"              <TD align=\"center\" height=\"25\" width=\"27%\" >发卡日期：</td>"
+"              <TD height=\"25\" width=\"24%\" >"
+"                <INPUT datasrc=\"#eatery\" datafld=\"createdt\" isnull=true class=\"xlanddate\" style=\"width:98%;\" type=\"text\" size=\"11\" name=\"消费发卡日期\" />"
+"              </td>"
+"            </tr>"
+"            <TR>"
+"              <TD align=\"center\" height=\"25\" width=\"24%\" >消费级别：</td>"
+"              <TD height=\"25\" width=\"24%\" >"
+"                <SELECT datasrc=\"#eatery\" datafld=\"elevel\" isnull=true class=\"xlandselect\" size=\"1\" style=\"WIDTH: 98%;\" name=\"消费级别\">"
+"                  <option value=\"\"></option><option value=\"1\">级别A</option><option value=\"2\">级别B</option>"
+"                  <option value=\"3\">级别C</option><option value=\"4\">级别D</option><option value=\"5\">级别D</option>"
+"                  <option value=\"6\">级别E</option><option value=\"7\">级别F</option><option value=\"8\">级别G</option>"
+"                  <option value=\"9\">级别H</option><option value=\"10\">级别I</option></SELECT></td>"
+"              <TD align=\"center\" height=\"25\" width=\"27%\" >有效期：</td>"
+"              <TD height=\"25\" width=\"24%\" >"
+"                <INPUT datasrc=\"#eatery\" datafld=\"validdt\" isnull=true class=\"xlanddate\" style=\"width:98%;\" type=\"text\" size=\"11\" name=\"消费有效期\" />"
+"              </td>"
+"            </tr>"
+"            <TR>"
+"              <TD align=\"center\" height=\"25\" width=\"24%\" >补助金额：</td>"
+"              <TD height=\"25\" width=\"24%\" >"
+"                <input type=\"text\" datasrc=\"#MasterTab\" datafld=\"balance2\" class=\"xlandinput\" size=\"1\" style=\"WIDTH: 98%;\" name=\"补助金额\" />"
+"                  </td>"
+"            </tr>"
//+"            <TR>"
//+"              <TD align=\"center\" height=\"19\" width=\"24%\" >有效权限：</td>"
//+"              <TD width=\"24%\" ><input id=\"Checkbox6\" type=\"checkbox\" name=\"C4\" value=\"ON\" onclick=\"chkall(this.checked,'dins')\" />全选</td>"
//+"              <TD align=\"center\" width=\"27%\" >　</td>"
//+"              <TD width=\"24%\" >"
//+"            </TR>"
+"            <TR>"
+"              <TD align=\"center\" width=\"99%\" colspan=\"4\" valign=\"middle\" height=100%>"
//+"                <div id=\"elist\" style=\"text-align:left;width:98%;height:98%;overflow-y:scroll;overflow-x:hidden;border:1px solid #666666;\">    　</td>"
+"            </tr>"
+"          </tbody>"
+"          <!--菜单二内容-->"
+"          <TBODY style=\"DISPLAY: none\">"
+"            <TR>"
+"              <TD align=\"center\" height=\"2\" width=\"99%\" colspan=\"4\" >　</td>"
+"            </tr>"
+"            <TR>"
+"              <TD align=\"center\" height=\"25\" width=\"24%\" >开始日期：</td>"
+"              <TD align=\"center\" height=\"25\" width=\"24%\" >"
+"                <INPUT datasrc=\"#door\" datafld=\"bDate\"  isnull=true class=\"xlanddate\" style=\"width:98%; \" type=\"text\" size=\"11\" name=\"门禁开始日期\" />"
+"              </td>"
+"              <TD align=\"center\" height=\"25\" width=\"27%\" >结束日期：</td>"
+"              <TD align=\"center\" height=\"25\" width=\"24%\" >"
+"                <INPUT datasrc=\"#door\" datafld=\"eDate\" class=\"xlanddate\" isnull=true style=\"width:98%; \" type=\"text\" size=\"11\" name=\"门禁结束日期\" />"
+"              </td>"
+"            </tr>"
+"            <TR>"
+"              <TD align=\"center\" height=\"19\" width=\"24%\" >时段编号：</td>"
+"              <TD height=\"19\" width=\"24%\" >"
+"                <select id=\"TimeNo\" datasrc=\"#door\" datafld=\"TimeNo\" isnull=true class=\"xlandselect\" DataSource=\"execute dbo.dictmtimes\" DataTextField=\"name\" DataValueField=\"value\" size=\"1\" style=\"WIDTH: 98%;\" name=\"门禁时段编号\"></select>"
+"              </td>"
+"              <TD align=\"center\" height=\"19\" width=\"27%\" >用户密码：</td>"
+"              <TD height=\"19\" width=\"24%\" >"
+"                <INPUT datasrc=\"#door\" datafld=\"doorkey\" class=\"xlandinput\" style=\"width:98%; \" type=\"text\" size=\"11\" name=\"姓名41\" />"
+"            </tr>"
+"            <TR>"
+"              <TD align=\"center\" height=\"19\" width=\"24%\" >有效权限：</td>"
+"              <TD height=\"19\" width=\"24%\" >"
+"                <input id=\"chkdoors\" type=\"checkbox\" name=\"C4\" value=\"ON\" onclick=\"chkall(this.checked,'doors')\" />全选</td>"
+"              </td>"
+"              <TD align=\"center\" height=\"19\" width=\"27%\" >卡类型：</td>"
+"              <TD height=\"19\" width=\"24%\" >"
+"                <SELECT datasrc=\"#door\" datafld=\"cardtype\"  isnull=true class=\"xlandselect\" size=\"1\" style=\"WIDTH: 98%;\" name=\"门禁卡类型\">"
+"                  <option value=\"\"></option><option value=\"1\">授权卡</option><option value=\"2\">操作员卡</option>"
+"                  <option value=\"3\">用户卡</option></SELECT></td>"
+"            </tr>"
+"            <TR>"
+"              <TD align=\"center\" width=\"99%\" colspan=\"4\" valign=\"middle\" >"
+"                <div id=\"dlist\" style=\"text-align:left;width:98%;height:98%;overflow-y:scroll;overflow-x:hidden;border:1px solid #666666;\">    　</td>"
+"            </tr>"
+"          </tbody>"
+"          <TBODY style=\"DISPLAY: none\">"
+"            <TR>"
+"              <TD align=\"center\" height=\"2\" width=\"99%\" colspan=\"4\" >　</td>"
+"            </tr>"
+"            <TR>"
+"              <TD align=\"center\" height=\"25\" width=\"24%\" >发卡日期：</td>"
+"              <TD align=\"center\" height=\"25\" width=\"24%\" >"
+"        <INPUT datasrc=\"#kq\" datafld=\"createdt\" class=\"xlanddate\" style=\"width:98%;\" type=\"text\" size=\"11\" name=\"姓名42\" /></td>"
+"              <TD align=\"center\" height=\"25\" width=\"27%\" >有效期：</td>"
+"              <TD align=\"center\" height=\"25\" width=\"24%\" >"
+"        <INPUT datasrc=\"#kq\" datafld=\"validdt\" class=\"xlanddate\" style=\"width:98%;\" type=\"text\" size=\"11\" name=\"姓名43\" /></td>"
+"            </tr>"
+"            <TR>"
+"              <TD align=\"center\" height=\"25\" width=\"24%\" >有效权限：</td>"
+"              <TD align=\"center\" height=\"25\" width=\"24%\" >"
+"        <input id=\"chkkqs\" type=\"checkbox\" name=\"C4\" value=\"ON\" onclick=\"chkall(this.checked,'kqs')\" />全选</td>"
+"              <TD align=\"center\" height=\"25\" width=\"27%\" ></td>"
+"              <TD align=\"center\" height=\"25\" width=\"24%\" >"
+"        </td>"
+"            </tr>"
+"            <TR>"
+"              <TD align=\"center\" width=\"99%\" colspan=\"4\" ><div id=\"kqlist\" style=\"text-align:left;width:98%;height:98%;overflow-y:scroll;overflow-x:hidden;border:1px solid #666666;\">    　</td>"
+"            </tr>"
+"          </tbody>"
+"          <TBODY style=\"DISPLAY: none\">"
+"            <TR>"
+"              <TD align=\"center\" height=\"2\" width=\"99%\" colspan=\"4\" >　</td>"
+"            </TR>"
+"            <TR>"
+"              <TD align=\"right\" width=\"24%\" >发卡日期：</TD>"
+"              <TD width=\"24%\" >"
+"	                <INPUT datasrc=\"#park\" datafld=\"createdt\" class=\"xlanddate\" style=\"width:98%;\" type=\"text\" size=\"11\" /></TD>"
+"              <TD align=\"right\" width=\"27%\" >有效期限：</TD>"
+"              <TD width=\"24%\" >"
+"                <INPUT datasrc=\"#park\" datafld=\"validdt\" class=\"xlanddate\" style=\"width:98%;\" type=\"text\" size=\"11\"/></TD>"
+"            </TR>"
+"            <TR>"
+"              <TD align=\"right\" width=\"24%\" >类　　型：</td>"
+"              <TD width=\"24%\" >"
+"                <SELECT id=\"parkct\" datasrc=\"#park\" datafld=\"card_type\" class=\"xlandselect\" size=\"1\" style=\"WIDTH: 98%;\" name=\"D9\">"
+"                  <option value=\"\"></option>"
+"                  <option value=\"1\">操作员卡</option>"
+"                  <option value=\"2\">期卡</option>"
+"                  <option value=\"3\">时段卡</option>"
+"                  <option value=\"4\">临时卡</option>"
+"                  <option value=\"5\">免费卡</option>"
+"                  <option value=\"6\">临免卡</option>"
+"                  <option value=\"7\">贵宾卡</option>"
+"                  <option value=\"8\">一卡通</option>"
+"                </SELECT>"
+"              </td>"
+"              <TD align=\"right\" width=\"27%\" >车辆类型：</td>"
+"              <TD width=\"24%\" >"
+"                <SELECT id=\"Select5\" datasrc=\"#park\" datafld=\"car_type\" class=\"xlandselect\" size=\"1\" style=\"WIDTH: 98%;\" name=\"D9\">"
+"                  <option value=\"\"></option>"
+"                  <option value=\"1\">小车</option>"
+"                  <option value=\"2\">中型车</option>"
+"                  <option value=\"3\">大车</option>"
+"                  <option value=\"4\">摩托车</option>"
+"              </td>"
+"            </tr>"
+"            <TR>"
+"              <TD align=\"right\"  height=\"19\" width=\"24%\" >车辆颜色：</td>"
+"              <TD width=\"24%\" >"
+"                <SELECT id=\"Select6\" datasrc=\"#park\" datafld=\"car_color\" class=\"xlandselect\" size=\"1\" style=\"WIDTH: 98%;\" name=\"D9\">"
+"                  <option value=\"\"></option>"
+"                  <option value=\"1\">黑</option>"
+"                  <option value=\"2\">红</option>"
+"                  <option value=\"3\">灰</option>"
+"                  <option value=\"4\">白</option>"
+"                  <option value=\"5\">黄</option>"
+"                  <option value=\"6\">绿</option>"
+"                  <option value=\"7\">兰</option>"
+"                </SELECT>"
+"              </td>"
+"              <TD align=\"right\" width=\"27%\" >车牌号码：</TD>"
+"              <TD width=\"24%\" >"
+"                <INPUT datasrc=\"#park\" datafld=\"carno\" class=\"xlandinput\" style=\"width:98%;\" type=\"text\" size=\"11\"  />"
+"              </TD></TR>"
+"            <TR>"
+"              <TD align=\"right\" width=\"24%\" >时　段1：</td>"
+"              <TD width=\"24%\" >"
+"                <select id=\"timesec1\" datasrc=\"#park\" datafld=\"timesec1\" class=\"xlandselect\" size=\"1\" style=\"WIDTH: 98%;\" name=\"D9\">"
+"                  <option value=\"\"></option>"
+"                  <option value=\"1\">时段一</option>"
+"                  <option value=\"2\">时段二</option>"
+"</select>"
+"              </td>"
+"              <TD align=\"right\" width=\"27%\" >时　段2：</td>"
+"              <TD width=\"24%\" >"
+"                <select id=\"timesec2\" datasrc=\"#park\" datafld=\"timesec2\" class=\"xlandselect\" size=\"1\" style=\"WIDTH: 98%;\" name=\"D9\">"
+"                  <option value=\"\"></option>"
+"                  <option value=\"1\">时段一</option>"
+"                  <option value=\"2\">时段二</option>"
+"</select>"
+"              </td>"
+"            </tr>"
+"              <TD align=\"right\" width=\"24%\">车场设备：</td>"
+"              <TD colspan=\"2\">"
+"                <input id=\"chkparks\" type=\"checkbox\" name=\"C4\" value=\"ON\" title=\"全选\" onclick=\"chkall(this.checked,'parks')\" />选择所有设备"
+"              </td>"
+"            </tr>"
+"            <TR>"
//+"              <TD align=\"right\" height=\"80\" width=\"24%\"><input id=\"Checkbox6\" type=\"checkbox\" name=\"C4\" value=\"ON\" title=\"全选\" onclick=\"chkall(this.checked,'parks')\" />车　场：</td>"
+"              <TD align=\"center\" colspan=\"4\">"
+"                <div id=\"parklist\" style=\"text-align:left;width:98%;height:170px;overflow-y:scroll;overflow-x:hidden;border:1px solid #666666;\">"
+"              </td>"
+"            </tr>"
+"            <TR><TD width=\"24%\" align=\"right\">所属车位：</td>"
+"              <TD align=\"center\" colspan=3>1、<INPUT datasrc=\"#park\" datafld=\"park_stall1\" class=\"xlandinput\" style=\"width:50px;\" type=\"text\" size=\"11\"  />"
+"              　2、<INPUT datasrc=\"#park\" datafld=\"park_stall2\" class=\"xlandinput\" style=\"width:50px;\" type=\"text\" size=\"11\"  />"
+"              　3、<INPUT datasrc=\"#park\" datafld=\"park_stall3\" class=\"xlandinput\" style=\"width:50px;\" type=\"text\" size=\"11\"  />"
+"              </TD></TR>"
+"            <TR>"
+"          </tbody>"
+"          <TBODY style=\"DISPLAY: none\">"
+"            <TR>"
+"              <TD align=\"center\" height=\"2\" width=\"99%\" colspan=\"4\" >　</td>"
+"            </tr>"
+"            <TR>"
+"              <TD align=\"center\" height=\"25\" width=\"24%\" >发卡日期：</td>"
+"              <TD align=\"center\" height=\"25\" width=\"24%\" >"
+"        <INPUT datasrc=\"#MasterTab\" datafld=\"createdt\" class=\"xlanddate\" style=\"width:98%;\" type=\"text\" size=\"11\" name=\"姓名44\" /></td>"
+"              <TD align=\"center\" height=\"25\" width=\"27%\" >有效期：</td>"
+"              <TD align=\"center\" height=\"25\" width=\"24%\" >"
+"        <INPUT datasrc=\"#MasterTab\" datafld=\"validdt\" class=\"xlanddate\" style=\"width:98%;\" type=\"text\" size=\"11\" name=\"姓名45\" /></td>"
+"            </tr>"
+"            <TR>"
+"              <TD align=\"center\" width=\"99%\" colspan=\"4\" >　</td>"
+"            </tr>"
+"          </tbody>"
+"        </table>"
+"      </td>"
+"    </tr>"
+"    <tr>"
+"      <td width=\"10%\" align=\"right\" height=\"23\">部　门：</td>"
+"      <td width=\"15%\" height=\"23\">"
+"        <INPUT datasrc=\"#MasterTab\" datafld=\"DEPARTMENT\" class=\"xlandinput\" size=\"11\" style=\"WIDTH: 98%;\"></select>"
+"      </td>"
+"    </tr>"
+"    <tr>"
+"      <td width=\"10%\" align=\"right\" height=\"23\">性　别：</td>"
+"      <td width=\"15%\" height=\"23\">"
+"        <INPUT id=\"SEX\"  datasrc=\"#MasterTab\" datafld=\"sex\" class=\"xlandinput\" title=\"双击更改\" style=\"width:98%; \"  ondblclick=\"changesex(this)\" type=\"text\" size=\"11\" />"
+"      </td>"
+"    </tr>"
+"    <tr>"
+"      <td width=\"10%\" align=\"right\">身份证号：</td>"
+"      <td width=\"15%\">"
+"        <INPUT id=\"IDCARD\"  datasrc=\"#MasterTab\" datafld=\"idcard\" class=\"xlandinput\" style=\"width:98%; \" type=\"text\" size=\"11\" />"
+"      </td>"
+"    </tr>"
+"    <tr>"
+"      <td width=\"10%\" align=\"right\">电　话：</td>"
+"      <td width=\"35%\" colspan=\"2\">"
+"        <INPUT id=\"HOMEPHONE\"  datasrc=\"#MasterTab\" datafld=\"homephone\" class=\"xlandinput\" style=\"width:98%; \" type=\"text\" size=\"11\" /></td>"
+"    </tr>"
+"    <tr>"
+"      <td width=\"10%\" align=\"right\">地　址：</td>"
+"      <td width=\"35%\" colspan=\"2\">"
+"        <INPUT id=\"ADDRESS\"  datasrc=\"#MasterTab\" datafld=\"address\" class=\"xlandinput\" style=\"width:98%; \" type=\"text\" size=\"11\" />"
+"      </td>"
+"    </tr>"
+"    <tr>"
+"      <td width=\"10%\" align=\"right\" height=\"23\">学　历：</td>"
+"      <td width=\"35%\" colspan=\"2\" height=\"23\">"
+"        <select id=\"CULTURE\"  datasrc=\"#MasterTab\" datafld=\"culture\" class=\"xlandinput\"  size=\"1\" style=\"WIDTH: 98%;\" name=\"D8\">"
+"            <option value=\"\"></option><option value=\"小学\">小学</option><option value=\"中学\">中学</option>"
+"            <option value=\"中专\">中专</option><option value=\"大专\">大专</option><option value=\"本科\">本科</option>"
+"            <option value=\"硕士\">硕士</option><option value=\"博士\">博士</option></select>"
+"      </td>"
+"    </tr>"
+"    <tr>"
+"      <td width=\"10%\" align=\"right\">入职日期：</td>"
+"      <td width=\"35%\" colspan=\"2\">"
+"        <INPUT id=\"POSTDATE\"  datasrc=\"#MasterTab\" datafld=\"POSTDATE\" class=\"xlanddate\" style=\"width:98%; \" type=\"text\" size=\"11\" name=\"姓名25\" />"
+"      </td>"
+"    </tr>"
+"    <tr>"
+"      <td width=\"10%\" align=\"right\" height=\"23\">员工类别：</td>"
+"      <td width=\"35%\" colspan=\"2\" height=\"23\">"
+"        <select id=\"EMPTYPEID\"  datasrc=\"#MasterTab\" datafld=\"emptypeid\" onfocus=\"us_htmldict('edit',this.id)\" DataValueField=\"code\" DataTextField=\"name\" DataSource=\"resources:dict_employtype\" class=\"xlandinput\"  size=\"1\" style=\"WIDTH: 98%;\" name=\"D10\"></select>"
+"      </td>"
+"    </tr>"
+"    <tr>"
+"      <td width=\"10%\" align=\"right\">EMAIL地址：</td>"
+"      <td width=\"35%\" colspan=\"2\">"
+"        <INPUT id=\"EMAIL\" style=\"width:98%; \" datasrc=\"#MasterTab\" datafld=\"email\" class=\"xlandinput\" type=\"text\" size=\"11\" name=\"姓名22\" />"
+"      </td>"
+"    </tr>"
+"    <tr>"
+"      <td width=\"10%\" align=\"right\">备　注：</td>"
+"      <td width=\"35%\" colspan=\"2\">"
+"        <INPUT id=\"MEMORY\"  datasrc=\"#MasterTab\" datafld=\"MEMORY\" class=\"memory\" style=\"width:98%; \" type=\"text\" size=\"11\" name=\"姓名28\" />"
+"      </td>"
+"    </tr>"
+"    <tr rowspan=2>"
+"      <td width=\"45%\" align=center colspan=\"3\" style=\"color: #FF0000;font-weight: bold\" id='warnmsg'>　</td>"
+"    </tr>"
+"  </tbody>"
+"</table>";
  var tableinit = "<div style=\"BORDER-RIGHT: 2px groove; float:left;BORDER-TOP: 2px groove; BACKGROUND: transprant; BORDER-LEFT: 2px groove; WIDTH:260;HEIGHT:240; BORDER-BOTTOM: 2px groove;TEXT-ALIGN:center\">"
                  + "<br /><br />卡序列号：<INPUT id=\"inputinit\" disabled style=\"width:130px;font-weight: bold\" type=\"text\" size=\"11\" name=\"x\" />"
                  + "<br /><br /><span style='display:none'>卡　　号：</span><INPUT id=\"inputuserno\" style=\"width:130px;display:none\" type=\"text\" size=\"11\" name=\"x\" />"
                  +"</div>"
                  +"<div style=\"BORDER-RIGHT: 2px groove; BORDER-TOP: 2px groove; float:right;BACKGROUND: transprant; BORDER-LEFT: 2px groove; WIDTH:305;HEIGHT:25; line-height:25px;BORDER-BOTTOM: 2px groove;TEXT-ALIGN:center;\">"
                  +"操作日志</div>"
                  +"<div id=\"intrnt\" style=\"overflow-y:auto;padding:3;BORDER-RIGHT: 2px groove; BORDER-TOP: 2px groove; float:right;BACKGROUND: transprant; BORDER-LEFT: 2px groove; WIDTH:305;HEIGHT:211; BORDER-BOTTOM: 2px groove;TEXT-ALIGN:center\">"
                  +"<span style=\"width:120px\">卡序列号</span><span style=\"width:140px\">卡号</span></div>";
  
  var tablecharge ="<DIV style=\"font-size: 10pt;BORDER-RIGHT: 2px groove;float:left;BORDER-TOP: 2px groove; BACKGROUND: transprant; BORDER-LEFT: 2px groove; WIDTH:200;HEIGHT:285; BORDER-BOTTOM: 2px groove;\">"
                  + "<br /><span style=\"width:80px\">部　　门:</span><SELECT id=\"department\" DataValueField=\"name\" DataTextField=\"name\" DataSource=\"resources:dict_organize\" class=\"xlandselect\" size=\"1\" style=\"WIDTH: 100;\" name=\"D9\"></SELECT>"
                  + "<br /><span style=\"width:80px\">卡　　号:</span><INPUT id=\"card_no\" readonly=true class=\"xlandinput\" style=\"width:100px\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">用户编号:</span><INPUT id=\"empcode\" readonly=true class=\"xlandinput\" style=\"width:100px\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">姓　　名:</span><INPUT id=\"name\" readonly=true class=\"xlandinput\" style=\"width:50px;\" type=\"text\" size=\"11\"  />"
                  +"&nbsp;<input id=\"cbtnfind\" type=\"button\" class=\"flatbtn\" style=\"width:43px\" disabled=true value=\"查询\" onclick=\"dlgwinpre('1','grid')\" />"
                  + "<br /><span style=\"width:80px\">充值方式:</span><SELECT  id=\"chargtype\" onchange=\"_chgctype()\" class=\"xlandselect\" size=\"1\" style=\"WIDTH: 100;\" name=\"D9\">"
                  +"<option value=\"\"></option><option value=\"1\">有卡充值</option><option value=\"2\">无卡充值</option></SELECT>"
                  + "<br /><span style=\"width:80px\">原有余额:</span><INPUT  id=\"balance\" readonly=true  class=\"xlandinput\" style=\"width:100px;\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">原有补助:</span><INPUT  id=\"balance2\" readonly=true  class=\"xlandinput\" style=\"width:100px;\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">现金充值:</span><INPUT id=\"AddAmt\" cls=true  isnull=true name=\"充值金额\" onblur=\"value =isNaN(parseFloat(value))? 0:parseFloat(value)\" class=\"xlandinput\" style=\"width:100px;\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">补助充值:</span><INPUT id=\"AddAmt2\" cls=true  readonly=true  name=\"补助充值\" onblur=\"value =isNaN(parseFloat(value))? 0:parseFloat(value)\" class=\"xlandinput\" style=\"width:100px;\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">原有效期:</span><INPUT id=\"oldvaliddt\" readonly=true style=\"width:100px\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">现有效期:</span><INPUT id=\"ValidTime\" cls=true isnull=true name=\"现有效期\" class=\"inputdate\" style=\"width:100px;\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">备　　注:</span><INPUT id=\"Remark\" class=\"xlandinput\" style=\"width:100px\" type=\"text\" size=\"11\"  />"
                  +"<br /></div>"
                  +"<div style=\"BORDER-RIGHT: 2px groove; BORDER-TOP: 2px groove; float:right;BACKGROUND: transprant; BORDER-LEFT: 2px groove; WIDTH:390;HEIGHT:25; line-height:25px;BORDER-BOTTOM: 2px groove;TEXT-ALIGN:center;\">"
                  +"操作日志</div>"
                  +"<div id=\"chargernt\" style=\"overflow-y:auto;padding:2;BORDER-RIGHT: 2px groove; BORDER-TOP: 2px groove; float:right;BACKGROUND: transprant; BORDER-LEFT: 2px groove; WIDTH:390;HEIGHT:226; BORDER-BOTTOM: 2px groove;TEXT-ALIGN:left\">"
                  +"<span style=\"width:70px\">卡序列号</span><span style=\"width:60px\">卡号</span><span style=\"width:60px\">姓名</span><span style=\"width:70px\">充值金额</span><span style=\"width:80px\">有效期</span></div>";

  var tabledelay = "<DIV style=\"BORDER-RIGHT: 2px groove;float:left;BORDER-TOP: 2px groove; BACKGROUND: transprant; BORDER-LEFT: 2px groove; WIDTH:200;HEIGHT:255; BORDER-BOTTOM: 2px groove;\">"
                  + "<br /><span style=\"width:80px\">部　　门:</span><SELECT id=\"department\" DataValueField=\"name\" DataTextField=\"name\" DataSource=\"resources:dict_organize\" class=\"xlandselect\" size=\"1\" style=\"WIDTH: 100;\" name=\"D9\"></SELECT>"
                  + "<br /><span style=\"width:80px\">卡序列号:</span><INPUT id=\"cardid\" cls=true  readonly=true class=\"xlandinput\" style=\"width:100px;\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">卡　　号:</span><INPUT id=\"card_no\" isnull=true name=\"卡号\" cls=true  readonly=true class=\"xlandinput\" style=\"width:100px\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">用户编号:</span><INPUT id=\"empcode\" cls=true  readonly=true class=\"xlandinput\" style=\"width:100px\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">姓　　名:</span><INPUT id=\"name\" cls=true  readonly=true class=\"xlandinput\" style=\"width:50px;\" type=\"text\" size=\"11\"  />"
                  +"&nbsp;<input id=\"cbtnfind\" type=\"button\" class=\"flatbtn\" style=\"width:43px\" disabled=true value=\"查询\" onclick=\"dlgwinpre('1','grid')\" />"
                  + "<br /><span style=\"width:80px\">延期方式:</span><SELECT id=\"chargtype\" onchange=\"_chgctype()\" class=\"xlandselect\" size=\"1\" style=\"WIDTH: 100;\" name=\"D9\">"
                  +"<option value=\"\"></option><option value=\"1\">有卡延期</option><option value=\"2\">无卡延期</option></SELECT>"
                  + "<br /><span style=\"width:80px\">余    额:</span><INPUT id=\"balance\"  cls=true name=\"余额\" class=\"xlandinput\" style=\"width:100px;\" type=\"text\" size=\"11\" disabled />"
                  + "<br /><span style=\"width:80px\">付款金额:</span><INPUT id=\"AddAmt\"  cls=true name=\"付款金额\" onblur=\"value =isNaN(parseFloat(value))? 0:parseFloat(value)\" class=\"xlandinput\" style=\"width:100px;\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">原有效期:</span><INPUT id=\"oldvaliddt\"  cls=true readonly=true style=\"width:100px\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">现有效期:</span><INPUT id=\"ValidTime\"  cls=true isnull=true name=\"现有效期\" class=\"inputdate\" style=\"width:100px;\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">备　　注:</span><INPUT id=\"Remark\" class=\"xlandinput\" style=\"width:100px\" type=\"text\" size=\"11\"  />"
                  +"<br /><span>　</span></div>"
                  +"<div style=\"BORDER-RIGHT: 2px groove; BORDER-TOP: 2px groove; float:right;BACKGROUND: transprant; BORDER-LEFT: 2px groove; WIDTH:390;HEIGHT:25; line-height:25px;BORDER-BOTTOM: 2px groove;TEXT-ALIGN:center;\">"
                  +"操作日志</div>"
                  +"<div id=\"chargernt\" style=\"overflow-y:auto;padding:2;BORDER-RIGHT: 2px groove; BORDER-TOP: 2px groove; float:right;BACKGROUND: transprant; BORDER-LEFT: 2px groove; WIDTH:390;HEIGHT:226; BORDER-BOTTOM: 2px groove;TEXT-ALIGN:left\">"
                  +"<span style=\"width:70px\">卡序列号</span><span style=\"width:60px\">卡号</span><span style=\"width:60px\">姓名</span><span style=\"width:70px\">付款金额</span><span style=\"width:80px\">有效期</span></div>";

  var tablelost = "<DIV style=\"BORDER-RIGHT: 2px groove;float:left;BORDER-TOP: 2px groove; BACKGROUND: transprant; BORDER-LEFT: 2px groove; WIDTH:200;HEIGHT:255; BORDER-BOTTOM: 2px groove;\">"
                  + "<br /><span style=\"width:80px\">部　　门:</span><SELECT id=\"department\" DataValueField=\"name\" DataTextField=\"name\" DataSource=\"resources:dict_organize\" class=\"xlandselect\" size=\"1\" style=\"WIDTH: 100;\" name=\"D9\"></SELECT>"
                  + "<br /><span style=\"width:80px\">卡序列号:</span><INPUT id=\"cardid\" cls=true  readonly=true class=\"xlandinput\" style=\"width:100px;\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">卡　　号:</span><INPUT id=\"card_no\" isnull=true name=\"卡号\" cls=true  readonly=true class=\"xlandinput\" style=\"width:100px\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">用户编号:</span><INPUT id=\"empcode\" cls=true  readonly=true class=\"xlandinput\" style=\"width:100px\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">姓　　名:</span><INPUT id=\"name\" cls=true  readonly=true class=\"xlandinput\" style=\"width:50px;\" type=\"text\" size=\"11\"  />"
                  +"&nbsp;<input id=\"cbtnfind\" type=\"button\" class=\"flatbtn\" style=\"width:43px\" value=\"查询\" onclick=\"dlgwinpre('1','grid')\" />"
                  + "<br /><span style=\"width:80px\">卡　　类:</span><INPUT id=\"cardtype\" cls=true readonly=true class=\"xlandinput\" style=\"width:100px;\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">押金金额:</span><INPUT  id=\"foregift\" cls=true readonly=true class=\"xlandinput\" style=\"width:100px;\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">卡上余额:</span><INPUT id=\"balance\" cls=true readonly=true class=\"xlandinput\" style=\"width:100px;\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">补助余额:</span><INPUT  id=\"balance2\" cls=true readonly=true  class=\"xlandinput\" style=\"width:100px;\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">有效期:</span><INPUT id=\"oldvaliddt\" cls=true  isnull=true name=\"有效期\" class=\"inputdate\" style=\"width:100px;\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">备　　注:</span><INPUT id=\"Remark\" class=\"xlandinput\" style=\"width:100px\" type=\"text\" size=\"11\"  />"
                  + "<br /><br />&nbsp;<input id=\"jg\" type=\"radio\" checked name=\"opchk\" onclick=\"chktype('解挂')\" value=\"解挂\"><span>解挂</span>"
                  +"<input id=\"gs\" type=\"radio\" name=\"opchk\" onclick=\"chktype('挂失')\" value=\"挂失\"><span>挂失</span>"
                  + "<input type=\"checkbox\" name=\"clearsign\" value=\"ON\" /><span>清除入场标志</span>"
                  +"<span>　</span></div>"
                  +"<div style=\"BORDER-RIGHT: 2px groove; BORDER-TOP: 2px groove; float:right;BACKGROUND: transprant; BORDER-LEFT: 2px groove; WIDTH:390;HEIGHT:25; line-height:25px;BORDER-BOTTOM: 2px groove;TEXT-ALIGN:center;\">"
                  +"操作日志</div>"
                  +"<div id=\"chargernt\" style=\"overflow-y:auto;padding:2;BORDER-RIGHT: 2px groove; BORDER-TOP: 2px groove; float:right;BACKGROUND: transprant; BORDER-LEFT: 2px groove; WIDTH:390;HEIGHT:254; BORDER-BOTTOM: 2px groove;TEXT-ALIGN:left\">"
                  +"<br /><span style=\"width:70px\">卡序列号</span><span style=\"width:60px\">卡号</span><span style=\"width:60px\">姓名</span><span style=\"width:70px\">卡余额</span><span style=\"width:80px\">有效期</span></div>";

  var tablequit = "<DIV style=\"BORDER-RIGHT: 2px groove;float:left;BORDER-TOP: 2px groove; BACKGROUND: transprant; BORDER-LEFT: 2px groove; WIDTH:200;HEIGHT:255; BORDER-BOTTOM: 2px groove;\">"
                  + "<br /><span style=\"width:80px\">部　　门:</span><SELECT id=\"department\" DataValueField=\"name\" DataTextField=\"name\" DataSource=\"resources:dict_organize\" class=\"xlandselect\" size=\"1\" style=\"WIDTH: 100;\" name=\"D9\"></SELECT>"
                  + "<br /><span style=\"width:80px\">卡序列号:</span><INPUT id=\"cardid\"  cls=true readonly=true class=\"xlandinput\" style=\"width:100px;\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">卡　　号:</span><INPUT id=\"card_no\" isnull=true name=\"卡号\" cls=true readonly=true class=\"xlandinput\" style=\"width:100px\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">用户编号:</span><INPUT id=\"empcode\" cls=true readonly=true class=\"xlandinput\" style=\"width:100px\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">姓　　名:</span><INPUT id=\"name\" cls=true readonly=true class=\"xlandinput\" style=\"width:50px;\" type=\"text\" size=\"11\"  />"
                  +"&nbsp;<input id=\"cbtnfind\" type=\"button\" class=\"flatbtn\" style=\"width:43px\" disabled=true value=\"查询\" onclick=\"dlgwinpre('1','grid')\" />"
                  + "<br /><span style=\"width:80px\">卡　　类:</span><INPUT id=\"cardtype\" readonly=true class=\"xlandinput\" style=\"width:100px\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">退卡方式:</span><SELECT id=\"chargtype\" onchange=\"_chgctype()\" class=\"xlandselect\" size=\"1\" style=\"WIDTH: 100;\" name=\"D9\">"
                  +"<option value=\"\"></option><option value=\"1\">有卡退卡</option><option value=\"2\">无卡退卡</option></SELECT>"
                  + "<br /><span style=\"width:80px\">押金金额:</span><INPUT  id=\"foregift\" cls=true readonly=true class=\"xlandinput\" style=\"width:100px;\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">卡上余额:</span><INPUT id=\"balance\" cls=true readonly=true class=\"xlandinput\" style=\"width:100px;\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">补助余额:</span><INPUT  id=\"balance2\" cls=true readonly=true  class=\"xlandinput\" style=\"width:100px;\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">退还金额:</span><INPUT id=\"allmoney\" cls=true class=\"xlandinput\" style=\"width:100px\" type=\"text\" size=\"11\"  />"
                  + "<br /><span style=\"width:80px\">备　　注:</span><INPUT id=\"Remark\" class=\"xlandinput\" style=\"width:100px\" type=\"text\" size=\"11\"  />"
                  +"<br /></div>"
                  +"<div style=\"BORDER-RIGHT: 2px groove; BORDER-TOP: 2px groove; float:right;BACKGROUND: transprant; BORDER-LEFT: 2px groove; WIDTH:390;HEIGHT:25; line-height:25px;BORDER-BOTTOM: 2px groove;TEXT-ALIGN:center;\">"
                  +"操作日志</div>"
                  +"<div id=\"chargernt\" style=\"overflow-y:auto;padding:1;BORDER-RIGHT: 2px groove; BORDER-TOP: 2px groove; float:right;BACKGROUND: transprant; BORDER-LEFT: 2px groove; WIDTH:390;HEIGHT:226; BORDER-BOTTOM: 2px groove\">"
                  +"<br /><span style=\"width:65px\">卡序列号</span><span style=\"width:50px\">卡号</span><span style=\"width:50px\">姓名</span><span style=\"width:65px\">退款金额</span><span style=\"width:130px\">时间</span></div>";


